"""CSV / Excel / PDF statement generation."""
import csv
import io
from datetime import datetime
from zoneinfo import ZoneInfo

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

IST = ZoneInfo("Asia/Kolkata")


def _d(iso: str) -> str:
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00")).astimezone(IST).strftime("%d-%m-%Y")
    except Exception:  # noqa: BLE001
        return iso[:10]


def _n(v: float) -> str:
    return f"{v:,.2f}" if v else ""


def _rows(stmt: dict):
    out = [["Date", "Particulars", "Debit", "Credit", "Balance"]]
    out.append(["", "Opening Balance", "", "", f"{stmt['opening_balance']:,.2f}"])
    for r in stmt["rows"]:
        out.append(
            [
                _d(r["entry_date"]),
                r.get("note") or ("Diya" if r["direction"] == "debit" else "Mila"),
                _n(r["amount"]) if r["direction"] == "debit" else "",
                _n(r["amount"]) if r["direction"] == "credit" else "",
                f"{r['running_balance']:,.2f}",
            ]
        )
    out.append(["", "Total", f"{stmt['total_debit']:,.2f}", f"{stmt['total_credit']:,.2f}", f"{stmt['closing_balance']:,.2f}"])
    return out


def to_csv(ledger_name: str, stmt: dict) -> bytes:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow([f"Ledger: {ledger_name}"])
    for row in _rows(stmt):
        w.writerow(row)
    return buf.getvalue().encode("utf-8-sig")


def to_xlsx(ledger_name: str, stmt: dict, subtitle: str = "") -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Statement"
    ws.append([f"Ledger: {ledger_name}"])
    ws["A1"].font = Font(bold=True, size=13)
    if subtitle:
        ws.append([subtitle])
    ws.append([])
    rows = _rows(stmt)
    head_row = ws.max_row + 1
    for row in rows:
        ws.append(row)
    for cell in ws[head_row]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="047857")
    for cell in ws[ws.max_row]:
        cell.font = Font(bold=True)
    widths = [14, 40, 16, 16, 18]
    for i, w in enumerate(widths):
        ws.column_dimensions[chr(65 + i)].width = w
    for row in ws.iter_rows(min_row=head_row + 1):
        for cell in row[2:]:
            cell.alignment = Alignment(horizontal="right")
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def to_pdf(ledger_name: str, stmt: dict, subtitle: str = "") -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=14 * mm, rightMargin=14 * mm, topMargin=14 * mm, bottomMargin=14 * mm)
    styles = getSampleStyleSheet()
    story = [Paragraph(f"<b>{ledger_name}</b> — Ledger Statement", styles["Title"])]
    if subtitle:
        story.append(Paragraph(subtitle, styles["Normal"]))
    bal = stmt["closing_balance"]
    story.append(Paragraph(f"Closing balance: <b>₹{abs(bal):,.2f} {'lena hai' if bal > 0 else 'dena hai' if bal < 0 else '(settled)'}</b>", styles["Normal"]))
    story.append(Spacer(1, 6 * mm))
    data = _rows(stmt)
    table = Table(data, colWidths=[24 * mm, 70 * mm, 28 * mm, 28 * mm, 32 * mm], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#047857")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
                ("ALIGN", (2, 1), (-1, -1), "RIGHT"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TEXTCOLOR", (2, 1), (2, -2), colors.HexColor("#B91C1C")),
                ("TEXTCOLOR", (3, 1), (3, -2), colors.HexColor("#047857")),
                ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#E4E4E7")),
                ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#F4F4F5")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(f"Generated by Munsiji • {datetime.now(IST).strftime('%d-%m-%Y %H:%M')}", styles["Italic"]))
    doc.build(story)
    return buf.getvalue()


FORMATS = {
    "csv": ("text/csv", "csv", to_csv),
    "excel": ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx", to_xlsx),
    "pdf": ("application/pdf", "pdf", to_pdf),
}


def build_export(fmt: str, ledger_name: str, stmt: dict, subtitle: str = ""):
    fmt = "excel" if fmt in ("xlsx", "xls") else fmt
    content_type, ext, fn = FORMATS[fmt]
    data = fn(ledger_name, stmt) if fmt == "csv" else fn(ledger_name, stmt, subtitle)
    safe = "".join(c if c.isalnum() else "_" for c in ledger_name).strip("_") or "ledger"
    filename = f"{safe}_statement.{ext}"
    return filename, content_type, data
