"""Iteration-10 export polish tests.

Verifies the rewritten `exports.py`:
- PDF uses the bundled FreeSans font (₹ glyph, no black boxes)
- PDF has Indian digit grouping, Dr/Cr suffix, In/Out for cash, page footer
- Long-note wrapping (no clipping)
- Excel: title block, styled header, real numeric cells with #,##0.00 format,
  freeze_panes below header, wider column B, Total row equals /statement,
  Closing text with ₹
- CSV: BOM + In/Out header for cash + Total row
- WhatsApp bot export path serves a valid ₹-bearing PDF
"""
from __future__ import annotations

import io
import os
import re
import time
import uuid

import pytest
import requests
from openpyxl import load_workbook
from pypdf import PdfReader

BASE_URL = os.environ.get("EXPO_PUBLIC_BACKEND_URL",
                          "https://whatsapp-munim.preview.emergentagent.com").rstrip("/") + "/api"
PIN = "3366"

RUPEE = "\u20b9"
BLACK_BOX = "\u25a0"
REPLACEMENT = "\ufffd"

# --------------------------------------------------------------------- helpers
INR_GROUP_RE = re.compile(r"\d{1,2}(?:,\d{2})+,\d{3}(?:\.\d+)?")  # e.g. 28,07,120.00 / 1,35,301.00


def _pdf_text(pdf_bytes: bytes) -> str:
    reader = PdfReader(io.BytesIO(pdf_bytes))
    return "\n".join(p.extract_text() or "" for p in reader.pages)


def _pdf_pages_text(pdf_bytes: bytes) -> list[str]:
    reader = PdfReader(io.BytesIO(pdf_bytes))
    return [p.extract_text() or "" for p in reader.pages]


# ------------------------------------------------------------------- fixtures
@pytest.fixture(scope="module")
def api():
    s = requests.Session()
    s.headers["Content-Type"] = "application/json"
    r = s.post(f"{BASE_URL}/auth/login", json={"pin": PIN}, timeout=15)
    assert r.status_code == 200, r.text
    s.headers["Authorization"] = f"Bearer {r.json()['access_token']}"
    return s


@pytest.fixture(scope="module")
def ledgers(api):
    r = api.get(f"{BASE_URL}/ledgers", timeout=15)
    assert r.status_code == 200
    data = r.json()
    party = next((l for l in data if l.get("kind") == "party" and l["name"] == "Biki [Mill]"), None)
    cash = next((l for l in data if l.get("kind") == "cash" and l["name"] == "Cash"), None)
    if not party:
        party = next((l for l in data if l.get("kind") == "party"), None)
    assert party and cash, "Need a party and the Cash ledger in seed data"
    return {"party": party, "cash": cash}


def _export(api, ledger_id: str, fmt: str) -> dict:
    r = api.post(f"{BASE_URL}/ledgers/{ledger_id}/export", json={"format": fmt}, timeout=30)
    assert r.status_code == 200, r.text
    return r.json()


def _download(url: str) -> requests.Response:
    r = requests.get(url, timeout=30)
    assert r.status_code == 200, f"download failed: {r.status_code} {r.text[:200]}"
    return r


# ================================================================== PDF party
class TestPdfParty:
    def test_party_pdf_has_rupee_and_freesans(self, api, ledgers):
        info = _export(api, ledgers["party"]["id"], "pdf")
        r = _download(info["url"])
        assert r.headers.get("content-type", "").startswith("application/pdf")
        assert r.content[:4] == b"%PDF", "not a PDF"
        # embedded FreeSans font (bundled TTF) - byte-level check on the PDF stream
        assert b"FreeSans" in r.content, "FreeSans font not embedded in PDF"

        text = _pdf_text(r.content)
        assert RUPEE in text, "rupee sign missing"
        for tok in ("Ledger Statement", "Opening Balance", "Total", ledgers["party"]["name"],
                    f"Debit ({RUPEE})", f"Credit ({RUPEE})", f"Balance ({RUPEE})",
                    f"Closing balance: {RUPEE}"):
            assert tok in text, f"missing token in PDF text: {tok!r}"

        # No black-box / replacement chars from missing glyph
        assert BLACK_BOX not in text
        assert REPLACEMENT not in text
        # Dr/Cr suffix on party balance somewhere
        assert (" Dr" in text) or (" Cr" in text) or ("(settled)" in text)


# ==================================================================== PDF cash
class TestPdfCash:
    def test_cash_pdf_headers_and_multipage_footer(self, api, ledgers):
        info = _export(api, ledgers["cash"]["id"], "pdf")
        r = _download(info["url"])
        assert r.headers.get("content-type", "").startswith("application/pdf")
        assert b"FreeSans" in r.content

        pages = _pdf_pages_text(r.content)
        text = "\n".join(pages)
        assert RUPEE in text
        assert BLACK_BOX not in text and REPLACEMENT not in text
        for tok in (f"In ({RUPEE})", f"Out ({RUPEE})", f"Balance ({RUPEE})", "cash in hand"):
            assert tok in text, f"cash PDF missing: {tok!r}"
        # Multi-page footer: Generated by Munsiji + Page N on page 1 and last page
        assert len(pages) >= 1
        for label, page_text in (("first", pages[0]), ("last", pages[-1])):
            assert "Generated by Munsiji" in page_text, f"footer missing on {label} page"
            assert re.search(r"Page \d+", page_text), f"page number missing on {label} page"

        # Indian-grouped numbers appear somewhere
        assert INR_GROUP_RE.search(text) or re.search(r"\b\d{1,3}(?:,\d{2,3})*\.\d{2}\b", text), \
            "no formatted numbers found"


# ============================================================== PDF wrap sanity
class TestPdfLongNoteWrap:
    def test_long_note_wraps_without_error(self, api):
        rid = f"EXPTEST_{uuid.uuid4().hex[:6]}"
        # Party ledgers require a group_id — grab any existing group
        gs = api.get(f"{BASE_URL}/groups", timeout=15).json()
        gid = gs[0]["id"]
        cl = api.post(f"{BASE_URL}/ledgers",
                      json={"name": rid, "kind": "party", "group_id": gid}, timeout=15)
        assert cl.status_code in (200, 201), cl.text
        lid = cl.json()["id"]
        note = ("lambi note wali entry " * 9)[:180]  # ~180 chars, spaces regularly
        try:
            t = api.post(f"{BASE_URL}/transactions",
                         json={"ledger_id": lid, "direction": "debit", "amount": 111.0,
                               "note": note, "mode": "cash"}, timeout=15)
            assert t.status_code in (200, 201), t.text

            info = _export(api, lid, "pdf")
            r = _download(info["url"])
            assert r.status_code == 200
            text = _pdf_text(r.content)
            # First few words of the long note must appear (wrapping, not clipped)
            assert "lambi note wali entry" in text, "long note beginning not present in PDF"
            assert BLACK_BOX not in text and REPLACEMENT not in text
        finally:
            api.delete(f"{BASE_URL}/ledgers/{lid}", timeout=15)


# ======================================================================= Excel
class TestExcel:
    def test_party_excel(self, api, ledgers):
        info = _export(api, ledgers["party"]["id"], "excel")
        r = _download(info["url"])
        ct = r.headers.get("content-type", "")
        assert "spreadsheetml" in ct, f"content-type: {ct}"
        wb = load_workbook(io.BytesIO(r.content))
        ws = wb.active
        assert ws["A1"].value == f"{ledgers['party']['name']} — Ledger Statement"

        # Find header row
        head = None
        head_row_idx = None
        for row in ws.iter_rows(min_row=1, max_row=15, values_only=False):
            vals = [c.value for c in row]
            if vals[:5] == ["Date", "Particulars", f"Debit ({RUPEE})",
                            f"Credit ({RUPEE})", f"Balance ({RUPEE})"]:
                head = vals
                head_row_idx = row[0].row
                break
        assert head is not None, "header row not found in party Excel"

        # freeze_panes just below header
        fp = ws.freeze_panes
        assert fp is not None
        assert fp.endswith(str(head_row_idx + 1)), f"freeze_panes={fp}, expected below row {head_row_idx}"

        # col B width >= 40
        b_width = ws.column_dimensions["B"].width or 0
        assert b_width >= 40, f"col B width={b_width}"

        # find Total row and last row (Closing:)
        total_row = None
        closing_row = None
        for row in ws.iter_rows(min_row=head_row_idx + 1, values_only=False):
            b = row[1].value if len(row) > 1 else None
            if b == "Total":
                total_row = row
            if isinstance(b, str) and b.startswith("Closing:"):
                closing_row = row
        assert total_row is not None
        assert closing_row is not None
        assert RUPEE in closing_row[1].value

        # Total numeric cells + format
        for col_idx in (2, 3, 4):  # 0-based -> Debit/Credit/Balance columns are index 2,3,4
            cell = total_row[col_idx]
            assert isinstance(cell.value, (int, float)), f"Total col {col_idx} not numeric: {cell.value!r}"
            assert "#,##0.00" in (cell.number_format or ""), \
                f"Total col {col_idx} number_format={cell.number_format!r}"

        # Match to /statement
        st = api.get(f"{BASE_URL}/ledgers/{ledgers['party']['id']}/statement", timeout=15).json()
        assert round(total_row[2].value, 2) == round(st["total_debit"], 2)
        assert round(total_row[3].value, 2) == round(st["total_credit"], 2)
        assert round(total_row[4].value, 2) == round(st["closing_balance"], 2)

    def test_cash_excel_headers(self, api, ledgers):
        info = _export(api, ledgers["cash"]["id"], "excel")
        r = _download(info["url"])
        wb = load_workbook(io.BytesIO(r.content))
        ws = wb.active
        found = False
        for row in ws.iter_rows(min_row=1, max_row=15, values_only=True):
            if row[:5] == ("Date", "Particulars", f"In ({RUPEE})", f"Out ({RUPEE})", f"Balance ({RUPEE})"):
                found = True
                break
        assert found, "Cash excel header not In/Out"


# ========================================================================= CSV
class TestCsv:
    def test_party_csv_has_bom_and_total(self, api, ledgers):
        info = _export(api, ledgers["party"]["id"], "csv")
        r = _download(info["url"])
        assert r.headers.get("content-type", "").startswith("text/csv")
        assert r.content[:3] == b"\xef\xbb\xbf", "missing BOM"
        text = r.content.decode("utf-8-sig")
        assert "Date,Particulars,Debit,Credit,Balance" in text
        # A Total line with 3 numeric cols (2-decimal)
        assert re.search(r",Total,\d+\.\d{2},\d+\.\d{2},-?\d+\.\d{2}", text), \
            "Total row with raw 2-decimal numbers missing"

    def test_cash_csv_headers(self, api, ledgers):
        info = _export(api, ledgers["cash"]["id"], "csv")
        r = _download(info["url"])
        text = r.content.decode("utf-8-sig")
        assert "Date,Particulars,In,Out,Balance" in text


# =============================================================== WhatsApp bot
class TestBotExport:
    def test_bot_pdf_export(self, api):
        """POST /api/whatsapp/simulate for a party ledger PDF export. AI may take ~20s."""
        r = api.post(f"{BASE_URL}/whatsapp/simulate",
                     json={"text": "Biki mill ka ledger pdf bhejo"}, timeout=30)
        assert r.status_code == 200, r.text
        data = r.json()
        files = data.get("files") or []
        # If the bot asks for format, reply 'pdf'
        if not files:
            reply = (data.get("reply") or "").lower()
            assert "pdf" in reply or "format" in reply or "kis" in reply, \
                f"unexpected reply with no files: {data}"
            time.sleep(1)
            r2 = api.post(f"{BASE_URL}/whatsapp/simulate", json={"text": "pdf"}, timeout=30)
            assert r2.status_code == 200, r2.text
            files = (r2.json().get("files") or [])
        assert files, f"no files[] in bot reply: {data}"
        url = files[0].get("url")
        assert url
        pdf = _download(url).content
        assert pdf[:4] == b"%PDF"
        assert b"FreeSans" in pdf
        text = _pdf_text(pdf)
        assert RUPEE in text
        assert BLACK_BOX not in text and REPLACEMENT not in text
